- name: baseline
  color: 0a84ff
  description: Establish foundational tooling and quality gates
- name: ci
  color: 5856d6
  description: Changes affecting continuous integration workflows
- name: quality
  color: 34c759
  description: Improvements to linting, testing, or static analysis
