services:
  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel_network
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: laravel_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - laravel_network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_backend
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
      - backend_vendor:/var/www/html/vendor
    expose:
      - "8000"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: laravel
      REDIS_HOST: redis
      REDIS_PORT: 6379
      QUEUE_CONNECTION: redis
      BROADCAST_DRIVER: pusher
      PUSHER_APP_ID: predictive-patterns
      PUSHER_APP_KEY: local-key
      PUSHER_APP_SECRET: local-secret
      PUSHER_HOST: sockudo
      PUSHER_PORT: 6001
      PUSHER_SCHEME: http
      RUN_SEEDERS: "false"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      sockudo:
        condition: service_started
    networks:
      - laravel_network

  sockudo:
    image: sockudo/sockudo:latest
    container_name: sockudo
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    expose:
      - "6001"
    ports:
      - "9601:9601"
    environment:
      HOST: 0.0.0.0
      PORT: 6001
      METRICS_ENABLED: "true"
      METRICS_PORT: 9601
      SOCKUDO_DEFAULT_APP_ID: predictive-patterns
      SOCKUDO_DEFAULT_APP_KEY: local-key
      SOCKUDO_DEFAULT_APP_SECRET: local-secret
      SOCKUDO_ENABLE_CLIENT_MESSAGES: "true"
    networks:
      - laravel_network

  horizon:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_horizon
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
      - backend_vendor:/var/www/html/vendor
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: laravel
      REDIS_HOST: redis
      REDIS_PORT: 6379
      QUEUE_CONNECTION: redis
      BROADCAST_DRIVER: pusher
      PUSHER_APP_ID: predictive-patterns
      PUSHER_APP_KEY: local-key
      PUSHER_APP_SECRET: local-secret
      PUSHER_HOST: sockudo
      PUSHER_PORT: 6001
      PUSHER_SCHEME: http
      RUN_MIGRATIONS: "false"
      HORIZON_TRAINING_MEMORY: 1536
    deploy:
      resources:
        limits:
          memory: 3G
        reservations:
          memory: 1G
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      sockudo:
        condition: service_started
      backend:
        condition: service_started
    networks:
      - laravel_network
    command: php artisan horizon

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: laravel_frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    expose:
      - "3000"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://predictive-patterns.test
      - VITE_PROXY_TARGET=http://backend:8000
      - VITE_PUSHER_HOST=predictive-patterns.test
      - VITE_PUSHER_PORT=80
      - VITE_PUSHER_SCHEME=http
      - VITE_PUSHER_APP_KEY=local-key
    networks:
      - laravel_network

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend
      - sockudo
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
  backend_vendor:
  frontend_node_modules:
