name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  backend:
    name: Backend Quality Gate
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pcov, sqlite3
          coverage: pcov
          ini-values: pcov.directory=backend

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install Composer dependencies
        run: |
          composer update --prefer-dist --no-interaction --no-progress

      - name: Node dependencies
        run: npm install

      - name: Node audit (backend)
        run: npm audit --audit-level=high

      - name: Composer audit
        run: composer audit --locked --no-interaction

      - name: Laravel Pint
        run: ./vendor/bin/pint --test

      - name: Pest
        env:
          XDEBUG_MODE: coverage
        run: ./vendor/bin/pest --coverage

  frontend:
    name: Frontend Quality Gate
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm install

      - name: Node audit (high severity)
        run: npm audit --audit-level=high

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Vitest
        run: npm run test:unit

      - name: Playwright
        run: npm run test:e2e
